const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await b.newPage();await p.route('https://fonts.googleapis.com/**',r=>r.abort());let results=[];
for(const mode of ['fallback','native'])for(const width of [1440,980,768,720,390,320])for(const k of ['home','about']){
 await p.setViewportSize({width,height:900});await p.goto(`http://127.0.0.1:8766/after/${k}-${mode}.html`);await p.locator('img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await p.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));
 const rect=await p.locator('.gp-portrait').evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,x:e.getBoundingClientRect().x,overflow:document.documentElement.scrollWidth>innerWidth}));if(rect.overflow)console.log({mode,width,k,rect},await p.evaluate(()=>Array.from(document.querySelectorAll('*')).filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,rect:e.getBoundingClientRect().toJSON()})).slice(0,10)));assert.equal(rect.overflow,false);assert.ok(rect.width>=260&&rect.width<=420);assert.ok(Math.abs(rect.width-rect.height)<3,'portrait remains square');assert.ok(rect.x>=0&&rect.x+rect.width<=width);results.push({mode,width,k,...rect});
}
for(const variant of ['before','after'])for(const width of [1440,390])for(const key of ['home','about']){
 await p.setViewportSize({width,height:900});await p.goto(`http://127.0.0.1:8766/${variant}/${key}-fallback.html`);await p.locator('img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await p.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));await p.screenshot({path:`/workspace/grant-qa/3.3-${variant}-${key}-${width}.png`,fullPage:true});await p.locator(key==='home'?'#about':'.gp-biography').screenshot({path:`/workspace/grant-qa/3.3-${variant}-${key}-${width}-portrait.png`});
}
fs.writeFileSync('/workspace/grant-qa/portrait-results-3.3.json',JSON.stringify(results,null,2));await b.close();console.log('PASS: portrait size/aspect/no overflow across 24 page/layout/viewport combinations; 16 comparison screenshots.');})().catch(e=>{console.error(e);process.exit(1)});
