const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');let count=0;function check(v,s){assert.ok(v,s);count++}
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:390,height:844}});await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.route('https://fonts.gstatic.com/**',r=>r.abort());
for(const mode of ['fallback','native']){
 await p.goto(`http://127.0.0.1:8767/after/contact-${mode}.html`);const details=p.locator('[data-book-details]');check(!(await details.evaluate(e=>e.open)),`${mode} project starts with compact optional fields`);await p.locator('[name=request]').selectOption('assessment');check(await details.evaluate(e=>e.open),`${mode} assessment exposes book context`);
 await p.goto(`http://127.0.0.1:8767/after/enquiry-${mode}.html`);check(await p.locator('[name=request]').inputValue()==='assessment'&&await p.locator('[data-book-details]').evaluate(e=>e.open),`${mode} assessment page has correct default request and visible book fields`);
 await p.goto(`http://127.0.0.1:8767/after/contact-${mode}.html?service=Cover%20design`);check(await p.locator('[name=service]').inputValue()==='Cover design'&&await details.evaluate(e=>e.open),`${mode} preselected service is visible`);
 await p.locator('[name=name]').fill('Local Test');await p.locator('[name=email]').fill('test@example.test');await p.locator('[name=message]').fill('Local test only.');await p.locator('[name=consent]').check();await p.locator('[name=book_url]').fill('bad-url');await details.locator('summary').click();await p.locator('[type=submit]').click();check(await details.evaluate(e=>e.open),`${mode} invalid concealed optional URL opens disclosure`);check(await p.locator('[name=book_url]').evaluate(e=>e===document.activeElement),`${mode} invalid field receives focus`);
 await p.locator('[name=book_url]').fill('https://example.test/luma');await p.locator('[name=book]').fill('Luma test');await details.locator('summary').click();let submitted='';await p.route('**/mock-enquiry',r=>{submitted=r.request().postData();return r.fulfill({contentType:'application/json',body:JSON.stringify({success:false,data:{message:'Local rejected test.'}})})});await p.locator('[type=submit]').click();await p.waitForFunction(()=>document.querySelector('.gpc-form-status').dataset.state==='error');check(submitted.includes('https://example.test/luma')&&submitted.includes('Luma test')&&submitted.includes('Cover design'),`${mode} collapsed fields still submit entered values`);check(await p.locator('[name=book]').inputValue()==='Luma test'&&await p.locator('[name=message]').inputValue()==='Local test only.',`${mode} rejected submission retains all data`);await p.unroute('**/mock-enquiry');
}
for(const width of [768,844,1024]){await p.setViewportSize({width,height:390});await p.goto('http://127.0.0.1:8767/after/home-fallback.html');await p.locator('body').evaluate(e=>e.classList.add('admin-bar'));await p.locator('.gp-mobile-nav summary').click();const rect=await p.locator('.gp-mobile-nav nav').boundingBox();check(rect.y+rect.height<=390,`${width} logged-in short menu clears toolbar`)}
await b.close();const result=`PASS: ${count} optional disclosure, assessment default, visible preselection, invalid hidden field focus, retained multipart values and toolbar/menu assertions. All delivery intercepted locally.\n`;fs.writeFileSync('/workspace/grant-qa/optional-results-4.2.txt',result);console.log(result)})().catch(e=>{console.error(e);process.exit(1)});
