const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const defs=require('/workspace/GrantPublishing-Co/grant-publishing-site/pages.json');
const root='/workspace/grant-qa/fixtures/after';
const paths={};function route(k){const d=defs[k];return k==='home'?'/':(d.parent?route(d.parent).replace(/\/$/,''):'')+'/'+d.slug+'/'}
for(const k of Object.keys(defs))paths[route(k)]=k;
let mode='fallback',checks=0;function check(value,label){assert.ok(value,label);checks++}
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const ctx=await b.newContext();const p=await ctx.newPage();
await ctx.route('https://fonts.googleapis.com/**',r=>r.abort());await ctx.route('https://fonts.gstatic.com/**',r=>r.abort());
await ctx.route('http://127.0.0.1:8767/**',r=>{const url=new URL(r.request().url()),key=paths[url.pathname];return key?r.fulfill({contentType:'text/html',body:fs.readFileSync(`${root}/${key}-${mode}.html`)}):r.continue()});
await ctx.route('https://www.amazon.com/**',r=>r.fulfill({contentType:'text/html',body:'<title>Intercepted book destination</title>'}));
await ctx.route('https://www.linkedin.com/**',r=>r.fulfill({contentType:'text/html',body:'<title>Intercepted review destination</title>'}));
const services=Object.keys(defs).filter(k=>defs[k].parent==='services');
for(mode of ['fallback','native']){
 await p.setViewportSize({width:1440,height:900});
 for(const k of services){await p.goto(`http://127.0.0.1:8767${route(k)}`);const href=await p.locator('.gp-page-hero .gp-actions a').first().getAttribute('href');const expected=new URL(href,'http://127.0.0.1:8767').searchParams.get('service');await p.locator('.gp-page-hero .gp-actions a').first().click();await p.waitForLoadState('load');check(await p.locator('[name=service]').inputValue()===expected,`${mode} ${k} selected service`);check(await p.locator('[name=request]').inputValue()==='project',`${mode} ${k} selected project`)}
 await p.goto('http://127.0.0.1:8767/');await p.locator('.gp-header-cta a').click();await p.waitForLoadState('load');check(await p.locator('[name=request]').inputValue()==='assessment',`${mode} header assessment route`);
 await p.setViewportSize({width:390,height:844});await p.goto('http://127.0.0.1:8767/contact/');check(await p.locator('.gp-form-panel').evaluate(e=>e.getBoundingClientRect().top)<await p.locator('.gp-contact-aside').evaluate(e=>e.getBoundingClientRect().top),`${mode} mobile form precedes secondary contact context`);check(await p.locator('fieldset').count()===3,`${mode} semantic form groups`);
 for(const k of ['book-discovery','book-product-page','connected-catalog']){await p.goto(`http://127.0.0.1:8767${route(k)}`);const toc=p.locator('.gp-article-toc details');await toc.locator('summary').click();check(!(await toc.evaluate(e=>e.open)),`${mode} ${k} collapse contents`);await toc.locator('summary').click();await toc.locator('a').nth(1).click();const hash=new URL(p.url()).hash;const rect=await p.locator(hash).boundingBox();check(rect.y>=80&&rect.y<=130,`${mode} ${k} article anchor clears sticky header`)}
 await p.goto('http://127.0.0.1:8767/client-feedback/');check(await p.locator('blockquote').count()===5,`${mode} five genuine review entries`);check((await p.locator('body').textContent()).includes("Abdul outperformed himself in the creation of my children's book"),`${mode} exact John quote`);
 const book=p.locator('.gp-book-visual a').first();const popupPromise=ctx.waitForEvent('page');await book.click();const pop=await popupPromise;await pop.waitForLoadState();check(pop.url()==='https://www.amazon.com/dp/1947646168',`${mode} actual Kathryn cover destination`);await pop.close();
 const review=p.locator('.gp-review-john .gp-review-source a');const reviewPopup=ctx.waitForEvent('page');await review.click();const rp=await reviewPopup;await rp.waitForLoadState();check(rp.url()==='https://www.linkedin.com/services/page/a29863343146852122/',`${mode} actual LinkedIn review destination`);await rp.close();
 for(const width of [320,390,768,1024,1120,1121,1440]){await p.setViewportSize({width,height:390});await p.goto('http://127.0.0.1:8767/');const menu=p.locator('.gp-mobile-nav');if(width<=1120){check(await menu.isVisible(),`${mode} ${width} mobile navigation`);await menu.locator('summary').click();const bounds=await menu.locator('nav').boundingBox();check(bounds.y+bounds.height<=390,`${mode} ${width} short menu stays in viewport`);await p.keyboard.press('Tab');await p.keyboard.press('Escape');check(!(await menu.evaluate(e=>e.open))&&await menu.locator('summary').evaluate(e=>e===document.activeElement),`${mode} ${width} Escape focus return`)}else{check(await p.locator('.gp-nav').isVisible()&&!(await menu.isVisible()),`${mode} ${width} desktop navigation`)}}
 await p.setViewportSize({width:1120,height:900});await p.locator('.gp-mobile-nav summary').click();await p.keyboard.press('Tab');await p.setViewportSize({width:1121,height:900});await p.waitForFunction(()=>!document.querySelector('.gp-mobile-nav').open);check(await p.locator('.gp-wordmark').evaluate(e=>e===document.activeElement),`${mode} breakpoint restores desktop wordmark focus`);
}
await b.close();const result=`PASS: ${checks} navigation, service-prefill, assessment, form-order/group, article-contents/anchor, exact review, intercepted book/review destination and responsive menu assertions. No external submission or messages.\n`;fs.writeFileSync('/workspace/grant-qa/flows-results-4.0.txt',result);console.log(result)})().catch(e=>{console.error(e);process.exit(1)});
